### PR TITLE
Replace fitsdiff deprecated -d argument with -r

### PR DESCRIPTION
**Pull request by jhunkeler**
@pllim FYI

Backport of https://github.com/spacetelescope/pandokia/pull/3

### CODE REVIEW

**Comment by pllim** [comment]
LGTM :+1:

**Comment by mcara** [comment]
So this was the magic that makes it happen...

**Comment by pllim** [comment]
Is it? When does pandokia get new bug fix release?

**Comment by pllim** [comment]
Creature report reported that this fix is in. Thanks!

**Comment by mcara** [comment]
Thanks to the creature?

**Comment by pllim** [comment]
You are welcome https://github.com/pllim/creature_report

**Comment by mcara** [comment]
Thanks for clarification! I thought it was about that creature that wears sunglasses in his dark office...

**Comment by pllim** [comment]
No... https://www.youtube.com/watch?v=vyw1VW3xUjM

**Pull request merged**
